"""
Legacy-style email output for Daily Capacity Utilization Report.

STRICT RULES:
- Plaintext only
- Executive summary only
- Matches original legacy email behavior
"""

from typing import List, Optional

from radiology_reports.capacity_reporting.capacity_models import DailyCapacityResult
from radiology_reports.utils.config import config
from radiology_reports.utils.email_sender import EmailConfig, send_email


def _build_email_body(result: DailyCapacityResult) -> str:
    s = result.summary

    lines: list[str] = []

    # --------------------------------------------------
    # Header
    # --------------------------------------------------
    lines.append("RADIOLOGY REGIONAL")
    lines.append("DAILY CAPACITY UTILIZATION REPORT")
    lines.append("=" * 60)
    lines.append(f"Day of Service: {s.start_date}")
    lines.append("")

    # --------------------------------------------------
    # Network Summary
    # --------------------------------------------------
    lines.append("NETWORK SUMMARY")
    lines.append("-" * 40)
    lines.append(f"Total Active Sites:        {s.total_active_sites}")
    lines.append(f"Scheduled Weighted Units: {s.network_scheduled_weighted:,.2f}")
    lines.append(f"Network Capacity (90th):  {s.network_capacity_90th:,.2f}")
    lines.append(f"Network Utilization:      {s.network_utilization_pct}%")
    lines.append("")

    # --------------------------------------------------
    # Capacity Status Counts
    # --------------------------------------------------
    lines.append("SITE STATUS COUNTS")
    lines.append("-" * 40)
    lines.append(f"SITES OVER CAPACITY:  {s.sites_over}")
    lines.append(f"SITES AT CAPACITY:    {s.sites_at}")
    lines.append(f"SITES UNDER CAPACITY: {s.sites_under}")
    lines.append("")

    # --------------------------------------------------
    # Top 5 Utilization Sites
    # --------------------------------------------------
    lines.append("TOP 5 SITES BY UTILIZATION")
    lines.append("-" * 40)

    top5 = sorted(
        result.locations,
        key=lambda r: (r.pct_of_capacity or 0.0),
        reverse=True,
    )[:5]

    for r in top5:
        pct = f"{r.pct_of_capacity:.1%}" if r.pct_of_capacity is not None else "N/A"
        lines.append(
            f"{r.location:<18} "
            f"{r.weighted_units:>8.1f} weighted "
            f"({pct})  {r.status}"
        )

    # --------------------------------------------------
    # Unknown modality warning (legacy behavior)
    # --------------------------------------------------
    if result.unknown_modalities:
        lines.append("")
        lines.append("WARNING: Unknown modalities detected (missing weights):")
        for m in sorted(result.unknown_modalities):
            lines.append(f" - {m}")

    # --------------------------------------------------
    # Footer
    # --------------------------------------------------
    lines.append("")
    lines.append("This is an automated report generated by Radiology Regional Analytics.")
    lines.append("Please contact Analytics with questions or discrepancies.")

    return "\n".join(lines)


def email_daily_capacity(
    result: DailyCapacityResult,
    recipients: Optional[List[str]] = None,
) -> None:
    """
    Send legacy-style Daily Capacity Utilization email.
    """

    email_cfg = EmailConfig(
        smtp_server=config.SMTP_SERVER,
        smtp_port=config.SMTP_PORT,
        sender_email=config.SENDER_EMAIL,
        default_recipients=",".join(
            recipients or config.DEFAULT_RECIPIENTS
        ),
    )

    subject = f"Daily Capacity Utilization — DOS {result.summary.start_date}"

    send_email(
        config=email_cfg,
        subject=subject,
        body=_build_email_body(result),
        recipients=recipients or config.DEFAULT_RECIPIENTS,
    )
