"""
Email presentation for Daily Capacity Forecast.

Restores ORIGINAL email behavior:
- Executive summary
- Network totals
- Top utilization sites
- Plaintext, exec-readable
"""

from typing import List, Optional

from radiology_reports.forecasting.capacity_models import DailyCapacityResult
from radiology_reports.utils.config import config
from radiology_reports.utils.email_sender import (
    EmailConfig,
    send_email,
)


def _build_email_body(result: DailyCapacityResult) -> str:
    s = result.summary

    lines: list[str] = []

    lines.append("RADIOLOGY REGIONAL — DAILY CAPACITY REPORT")
    lines.append("=" * 55)
    lines.append(f"Report Date: {s.report_date}")
    lines.append(f"Scheduled Window: {s.start_date} to {s.end_date}")
    lines.append("")

    lines.append("NETWORK SUMMARY")
    lines.append("-" * 30)
    lines.append(f"Total Active Sites:        {s.total_active_sites}")
    lines.append(f"Scheduled Weighted Units: {s.network_scheduled_weighted:,.2f}")
    lines.append(f"Network Capacity (90th):  {s.network_capacity_90th:,.2f}")
    lines.append(f"Network Utilization:      {s.network_utilization_pct}%")
    lines.append("")

    lines.append("CAPACITY STATUS COUNTS")
    lines.append("-" * 30)
    lines.append(f"SITES OVER CAPACITY:  {s.sites_over}")
    lines.append(f"SITES AT CAPACITY:    {s.sites_at}")
    lines.append(f"SITES UNDER CAPACITY: {s.sites_under}")
    lines.append("")

    lines.append("TOP 5 HIGHEST UTILIZATION SITES")
    lines.append("-" * 40)

    top5 = sorted(
        result.locations,
        key=lambda r: (r.pct_of_capacity or 0.0),
        reverse=True
    )[:5]

    for r in top5:
        pct = f"{r.pct_of_capacity:.1%}" if r.pct_of_capacity is not None else "N/A"
        lines.append(
            f"{r.location:<18} "
            f"{r.weighted_units:>8.1f} weighted "
            f"({pct})  {r.status}"
        )

    if result.unknown_modalities:
        lines.append("")
        lines.append("WARNING — Unknown modalities detected (missing weights):")
        for m in sorted(result.unknown_modalities):
            lines.append(f" - {m}")

    lines.append("")
    lines.append("This is an automated report generated by Radiology Regional Analytics.")
    lines.append("Please contact Analytics if values appear inconsistent.")
    lines.append("")

    return "\n".join(lines)


def email_daily_capacity(
    results: List[DailyCapacityResult],
    recipients: Optional[List[str]] = None,
) -> None:
    """
    Send Daily Capacity Forecast emails.

    Mirrors ORIGINAL behavior:
    - One email per report window
    - Plaintext body
    """

    email_cfg = EmailConfig(
        smtp_server=config.SMTP_SERVER,
        smtp_port=config.SMTP_PORT,
        sender_email=config.SENDER_EMAIL,
        default_recipients=",".join(
            recipients or config.DEFAULT_RECIPIENTS
        ),
    )

    for result in results:
        subject = (
            f"Daily Capacity Report — "
            f"{result.summary.start_date} to {result.summary.end_date}"
        )

        body = _build_email_body(result)

        send_email(
            config=email_cfg,
            subject=subject,
            body=body,
            recipients=recipients or config.DEFAULT_RECIPIENTS,
        )
